# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: StableHLO
repo_url: https://github.com/openxla/stablehlo
repo_name: openxla/stablehlo
edit_uri: edit/main/docs/

theme:
  name: material
  logo: website/assets/openxla-logo-lockup-white.svg
  favicon: website/assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Noto
    code: Noto Sans Mono
  custom_dir: docs/website/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
  features:
    - content.code.copy    # Button to copy code snippets
    - content.action.edit  # Button to edit doc source
    - navigation.tabs      # Header tabs for nav items
    - navigation.top       # "Back to top" button
    - navigation.instant   # Ajax-style dynamic loading
    - toc.follow           # Scroll the TOC panel to follow the reader

extra_css:
  - website/stylesheets/openxla.css
extra_javascript:
  # MathJax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # Highlight.js
  - website/javascript/highlight.min.js
  - website/javascript/highlight-mlir.js

markdown_extensions:
  - pymdownx.superfences    # Nesting code fences and custom fence formats
  - pymdownx.highlight:     # Syntax highlighting for code blocks
      use_pygments: false   #   Use highlight.js to get MLIR syntax support
  - pymdownx.inlinehilite   # And inline code (just in case): `#!python range()`
  - pymdownx.snippets:      # Include files/snippets: --8<-- 'README.md'
      check_paths: true     #   and fail the build if file not found
  - def_list                # Basic definition lists
  - pymdownx.tasklist:      # GitHub-style task lists checkboxes
      custom_checkbox: true #   and use fancier icons
  - pymdownx.arithmatex:    # Inline and block equations with MathJax
      generic: true         #   (required for some reason)
  - toc:                    # Settings for table of contents
      permalink: 'link'     # Use Material font's "link" icon; see openxla.css
      toc_depth: 3          # Default number of headings to show in TOC
                            #   (can override in md file front matter)

plugins:
  - search                         # Search bar
  - git-revision-date-localized:   # Show file Git revision history at bottom
      enable_creation_date: true   #   with both created and last-edited date

nav:
  - Home: index.md
  - Specification:
    - StableHLO Specification: spec.md
