# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: StableHLO

repo_url: https://github.com/openxla/stablehlo
repo_name: openxla/stablehlo
edit_uri: edit/main/docs/

theme:
  name: material
  logo: website/assets/openxla-logo-lockup-white.svg
  favicon: website/assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  font:
    text: Noto
    code: Noto Sans Mono
  custom_dir: docs/website/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.sections
    - toc.follow

extra_css:
  - website/stylesheets/openxla.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: True
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
#  - mdx_truly_sane_lists:      # Allows nested lists with single newline
#      nested_indent: 2
  - toc:
      permalink: 'link'
      toc_depth: 3

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Specification:
    - StableHLO Specification Draft: spec_draft.md
